import { Document, Event, Task, Notification, ChatMessage, Template, InsurancePolicy, InsuranceSummary } from '@/types';

// Mock Documents
export const mockDocuments: Document[] = [
  {
    id: '1',
    title: 'Employment Agreement - ABC Corp',
    category: 'employment',
    documentType: 'Employment Agreement',
    status: 'active',
    filePath: '/documents/employment_abc.pdf',
    fileType: 'pdf',
    fileSize: 3200000,
    pages: 8,
    uploadedAt: new Date('2025-11-01'),
    signedDate: new Date('2025-11-01'),
    startDate: new Date('2025-11-15'),
    endDate: new Date('2026-05-15'),
    parties: ['You (Rajesh Kumar)', 'ABC Corporation', 'Mr. Suresh (HR Manager)'],
    tags: ['signed', 'important', 'contract'],
    country: 'India',
    region: 'Tamil Nadu',
    language: 'English',
    metadata: {
      salary: 1200000,
      noticePeriod: '60 days',
      probationPeriod: '6 months',
    },
    upcomingEvents: 3,
    pendingTasks: 2,
  },
  {
    id: '2',
    title: 'Rental Agreement - Landmark Apartments',
    category: 'property',
    documentType: 'Rental Agreement',
    status: 'active',
    filePath: '/documents/rental_landmark.pdf',
    fileType: 'pdf',
    fileSize: 1800000,
    pages: 12,
    uploadedAt: new Date('2025-10-15'),
    signedDate: new Date('2025-10-15'),
    startDate: new Date('2025-10-15'),
    endDate: new Date('2026-10-14'),
    parties: ['You', 'Landmark Properties Pvt Ltd', 'Mr. Kumar (Owner)'],
    tags: ['urgent', 'rent-due'],
    country: 'India',
    region: 'Tamil Nadu',
    language: 'English',
    metadata: {
      monthlyRent: 25000,
      securityDeposit: 50000,
      lockInPeriod: '11 months',
    },
    upcomingEvents: 1,
    pendingTasks: 0,
  },
  {
    id: '3',
    title: 'Non-Disclosure Agreement - ClientXYZ',
    category: 'employment',
    documentType: 'NDA',
    status: 'active',
    filePath: '/documents/nda_clientxyz.pdf',
    fileType: 'pdf',
    fileSize: 2300000,
    pages: 6,
    uploadedAt: new Date('2025-09-20'),
    signedDate: new Date('2025-09-20'),
    startDate: new Date('2025-09-20'),
    endDate: new Date('2027-09-20'),
    parties: ['You', 'XYZ Technologies Ltd'],
    tags: ['confidential', 'nda'],
    country: 'India',
    region: 'Tamil Nadu',
    language: 'English',
    upcomingEvents: 1,
    pendingTasks: 0,
  },
  {
    id: '4',
    title: 'Health Insurance Policy - Star Health',
    category: 'financial',
    documentType: 'Insurance Policy',
    status: 'expiring_soon',
    filePath: '/documents/health_insurance.pdf',
    fileType: 'pdf',
    fileSize: 5800000,
    pages: 24,
    uploadedAt: new Date('2024-12-01'),
    signedDate: new Date('2024-12-01'),
    startDate: new Date('2024-12-15'),
    endDate: new Date('2025-12-14'),
    parties: ['You', 'Star Health Insurance'],
    tags: ['insurance', 'health', 'renewal'],
    country: 'India',
    region: 'Tamil Nadu',
    language: 'English',
    metadata: {
      premium: 18500,
      coverage: 500000,
    },
    upcomingEvents: 1,
    pendingTasks: 1,
  },
];

// Mock Events
export const mockEvents: Event[] = [
  {
    id: '1',
    documentId: '1',
    eventType: 'contract_expiry',
    title: 'Employment Contract Expires - ABC Corp',
    description: 'Your employment contract with ABC Corp expires. You need to decide on renewal or give notice by Dec 8.',
    eventDate: new Date('2025-12-10'),
    priority: 'critical',
    isRecurring: false,
    responsibleParty: 'You',
    consequence: 'Auto-termination of employment. No severance unless negotiated.',
    advanceNoticeDays: 60,
    status: 'upcoming',
    reminders: [
      { id: 'r1', eventId: '1', daysBefore: 30, sent: true, sentAt: new Date('2025-11-10') },
      { id: 'r2', eventId: '1', daysBefore: 15, sent: true, sentAt: new Date('2025-11-25') },
      { id: 'r3', eventId: '1', daysBefore: 7, sent: true, sentAt: new Date('2025-12-03') },
      { id: 'r4', eventId: '1', daysBefore: 3, sent: false },
      { id: 'r5', eventId: '1', daysBefore: 1, sent: false },
    ],
  },
  {
    id: '2',
    documentId: '2',
    eventType: 'payment_due',
    title: 'Rent Payment Due',
    description: 'Monthly rent payment of ₹25,000 for Landmark Apartments',
    eventDate: new Date('2025-12-08'),
    priority: 'critical',
    isRecurring: true,
    recurrencePattern: 'monthly',
    status: 'upcoming',
    reminders: [
      { id: 'r6', eventId: '2', daysBefore: 3, sent: false },
      { id: 'r7', eventId: '2', daysBefore: 1, sent: false },
    ],
  },
  {
    id: '3',
    documentId: '4',
    eventType: 'renewal_date',
    title: 'Health Insurance Renewal',
    description: 'Star Health Insurance policy renewal. Premium: ₹18,500',
    eventDate: new Date('2025-12-15'),
    priority: 'high',
    isRecurring: true,
    recurrencePattern: 'yearly',
    status: 'upcoming',
    reminders: [
      { id: 'r8', eventId: '3', daysBefore: 30, sent: true },
      { id: 'r9', eventId: '3', daysBefore: 15, sent: false },
    ],
  },
  {
    id: '4',
    documentId: '3',
    eventType: 'review_date',
    title: 'NDA Quarterly Review',
    description: 'Quarterly review meeting with ClientXYZ regarding NDA obligations',
    eventDate: new Date('2025-12-20'),
    priority: 'medium',
    isRecurring: true,
    recurrencePattern: 'quarterly',
    status: 'upcoming',
    reminders: [
      { id: 'r10', eventId: '4', daysBefore: 7, sent: false },
    ],
  },
  {
    id: '5',
    documentId: '2',
    eventType: 'milestone',
    title: 'Lease Lock-in Period Ends',
    description: 'The 11-month lock-in period ends. You can now exit with 2 months notice.',
    eventDate: new Date('2026-01-10'),
    priority: 'medium',
    isRecurring: false,
    status: 'upcoming',
    reminders: [
      { id: 'r11', eventId: '5', daysBefore: 30, sent: false },
    ],
  },
];

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: '1',
    documentId: '1',
    eventId: '1',
    title: 'Research market salary for negotiation',
    description: 'Research current market rates for Software Engineer role in Chennai to prepare for contract renewal negotiation.',
    dueDate: new Date('2025-12-15'),
    priority: 'high',
    status: 'pending',
    createdAt: new Date('2025-11-15'),
  },
  {
    id: '2',
    documentId: '1',
    eventId: '1',
    title: 'Schedule renewal discussion with manager',
    description: 'Set up a meeting with manager to discuss contract renewal terms and expectations.',
    dueDate: new Date('2025-12-20'),
    priority: 'high',
    status: 'pending',
    createdAt: new Date('2025-11-15'),
  },
  {
    id: '3',
    documentId: '4',
    eventId: '3',
    title: 'Compare health insurance plans',
    description: 'Compare renewal premium with other providers and check for better coverage options.',
    dueDate: new Date('2025-12-10'),
    priority: 'medium',
    status: 'pending',
    createdAt: new Date('2025-11-20'),
  },
  {
    id: '4',
    title: 'Update leave tracker with pending leaves',
    dueDate: new Date('2025-12-10'),
    priority: 'low',
    status: 'in_progress',
    createdAt: new Date('2025-11-28'),
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'critical',
    title: 'Contract Expiry - ABC Corp',
    message: 'Your employment contract expires in 5 days (Dec 10, 2025). Decision needed by Dec 8.',
    documentId: '1',
    eventId: '1',
    isRead: false,
    createdAt: new Date('2025-12-05T09:00:00'),
    actions: [
      { label: 'View Document', action: 'view_document' },
      { label: 'Create Task', action: 'create_task' },
      { label: 'Snooze', action: 'snooze', variant: 'secondary' },
    ],
  },
  {
    id: '2',
    type: 'critical',
    title: 'Rent Payment Due',
    message: 'Monthly rent of ₹25,000 for Landmark Apartments is due in 3 days.',
    documentId: '2',
    eventId: '2',
    isRead: false,
    createdAt: new Date('2025-12-05T09:00:00'),
    actions: [
      { label: 'View Agreement', action: 'view_document' },
      { label: 'Mark Paid', action: 'mark_paid', variant: 'primary' },
      { label: 'Set Reminder', action: 'set_reminder', variant: 'secondary' },
    ],
  },
  {
    id: '3',
    type: 'info',
    title: 'Document Processed',
    message: 'NDA_ClientXYZ.pdf uploaded and analyzed. 2 events found, 3 reminders set, 1 task created.',
    documentId: '3',
    isRead: false,
    createdAt: new Date('2025-12-04T15:45:00'),
    actions: [
      { label: 'View Document', action: 'view_document' },
    ],
  },
  {
    id: '4',
    type: 'success',
    title: 'Task Completed',
    message: 'Task "Review NDA terms" has been marked as completed.',
    taskId: '4',
    isRead: true,
    readAt: new Date('2025-11-28T16:20:00'),
    createdAt: new Date('2025-11-28T16:20:00'),
  },
];

// Mock Chat Messages
export const mockChatMessages: ChatMessage[] = [
  {
    id: '1',
    role: 'assistant',
    content: "Hi! I'm your legal assistant. I can help you with questions about your documents, obligations, and deadlines.",
    timestamp: new Date('2025-12-05T12:30:00'),
  },
  {
    id: '2',
    role: 'user',
    content: 'Can I join a competitor after I resign?',
    timestamp: new Date('2025-12-05T14:35:00'),
  },
  {
    id: '3',
    role: 'assistant',
    content: `Based on your employment agreement with ABC Corp (uploaded Nov 1, 2025):

❗ You have a **12-month non-compete clause** that applies after resignation:

• Covers: "Fintech and digital payments sector"
• Geography: India
• Duration: 12 months from last working day
• Expires: May 15, 2027

⚠️ **Important Context:**
Non-compete clauses in India have limited enforceability under Section 27 of the Indian Contract Act. Courts often strike down overly broad restrictions.

💡 Recommendations:
1. Consult an employment lawyer
2. Review specific job role at new company
3. Consider negotiating removal during exit`,
    sources: [
      {
        documentId: '1',
        documentTitle: 'Employment Agreement - ABC Corp',
        section: 'Section 8',
        page: 5,
      },
    ],
    timestamp: new Date('2025-12-05T14:35:30'),
  },
];

// Mock Templates
export const mockTemplates: Template[] = [
  {
    id: '1',
    title: 'Residential Rental Agreement',
    category: 'property',
    country: 'India',
    region: 'Tamil Nadu',
    languages: ['English', 'Tamil'],
    description: 'Standard 11-month rental agreement for residential properties in Tamil Nadu, India. Compliant with Tamil Nadu Rent Control Act and Registration Act.',
    fields: [
      { id: 'landlord_name', name: 'landlord_name', label: 'Landlord Full Name', type: 'text', required: true },
      { id: 'landlord_address', name: 'landlord_address', label: 'Landlord Address', type: 'textarea', required: true },
      { id: 'tenant_name', name: 'tenant_name', label: 'Tenant Full Name', type: 'text', required: true },
      { id: 'tenant_address', name: 'tenant_address', label: 'Tenant Address', type: 'textarea', required: true },
      { id: 'property_address', name: 'property_address', label: 'Property Address', type: 'textarea', required: true },
      { id: 'monthly_rent', name: 'monthly_rent', label: 'Monthly Rent (INR)', type: 'number', required: true },
      { id: 'security_deposit', name: 'security_deposit', label: 'Security Deposit (INR)', type: 'number', required: true },
      { id: 'start_date', name: 'start_date', label: 'Lease Start Date', type: 'date', required: true },
      { id: 'lease_period', name: 'lease_period', label: 'Lease Period', type: 'select', required: true, options: ['11 months', '23 months', '35 months'] },
      { id: 'lock_in_period', name: 'lock_in_period', label: 'Lock-in Period', type: 'select', required: false, options: ['No lock-in', '6 months', '9 months', '11 months'] },
      { id: 'notice_period', name: 'notice_period', label: 'Notice Period', type: 'select', required: true, options: ['1 month', '2 months', '3 months'] },
      { id: 'maintenance_included', name: 'maintenance_included', label: 'Maintenance Included', type: 'checkbox', required: false },
    ],
    clauses: [
      'Rent payment due date (5th of every month)',
      'Security deposit refund terms',
      'Maintenance and repair responsibilities',
      'Termination and eviction clauses',
      'Subletting restrictions',
      'Force majeure clause',
    ],
  },
  {
    id: '2',
    title: 'Employment Agreement',
    category: 'employment',
    country: 'India',
    region: 'Tamil Nadu',
    languages: ['English'],
    description: 'Comprehensive employment agreement compliant with Indian labor laws, Shops and Establishments Act (Tamil Nadu), and IT/ITES industry standards.',
    fields: [
      { id: 'company_name', name: 'company_name', label: 'Company Name', type: 'text', required: true },
      { id: 'company_address', name: 'company_address', label: 'Company Address', type: 'textarea', required: true },
      { id: 'employee_name', name: 'employee_name', label: 'Employee Full Name', type: 'text', required: true },
      { id: 'employee_address', name: 'employee_address', label: 'Employee Address', type: 'textarea', required: true },
      { id: 'job_title', name: 'job_title', label: 'Job Title', type: 'text', required: true },
      { id: 'department', name: 'department', label: 'Department', type: 'text', required: true },
      { id: 'start_date', name: 'start_date', label: 'Employment Start Date', type: 'date', required: true },
      { id: 'annual_ctc', name: 'annual_ctc', label: 'Annual CTC (INR)', type: 'number', required: true },
      { id: 'probation_period', name: 'probation_period', label: 'Probation Period', type: 'select', required: true, options: ['3 months', '6 months', 'No probation'] },
      { id: 'notice_period', name: 'notice_period', label: 'Notice Period', type: 'select', required: true, options: ['30 days', '60 days', '90 days'] },
      { id: 'work_location', name: 'work_location', label: 'Work Location', type: 'text', required: true },
      { id: 'non_compete_period', name: 'non_compete_period', label: 'Non-compete Period (months)', type: 'select', required: false, options: ['None', '6', '12', '24'] },
    ],
    clauses: [
      'Job responsibilities and duties',
      'Compensation and benefits structure',
      'Probation period terms',
      'Termination and resignation clauses',
      'Confidentiality and data protection',
      'Intellectual property rights',
      'Non-compete and non-solicitation',
      'Leave and working hours policy',
    ],
  },
  {
    id: '3',
    title: 'Mutual Non-Disclosure Agreement (NDA)',
    category: 'business',
    country: 'India',
    region: 'Tamil Nadu',
    languages: ['English'],
    description: 'Two-way NDA for protecting confidential information shared between two parties. Suitable for business collaborations, partnerships, and vendor relationships.',
    fields: [
      { id: 'party1_name', name: 'party1_name', label: 'Party 1 Name', type: 'text', required: true },
      { id: 'party1_address', name: 'party1_address', label: 'Party 1 Address', type: 'textarea', required: true },
      { id: 'party2_name', name: 'party2_name', label: 'Party 2 Name', type: 'text', required: true },
      { id: 'party2_address', name: 'party2_address', label: 'Party 2 Address', type: 'textarea', required: true },
      { id: 'purpose', name: 'purpose', label: 'Purpose of Agreement', type: 'textarea', required: true },
      { id: 'start_date', name: 'start_date', label: 'Effective Date', type: 'date', required: true },
      { id: 'duration_years', name: 'duration_years', label: 'Agreement Duration', type: 'select', required: true, options: ['1 year', '2 years', '3 years', '5 years'] },
      { id: 'jurisdiction', name: 'jurisdiction', label: 'Jurisdiction', type: 'text', required: true, defaultValue: 'Chennai, Tamil Nadu' },
    ],
    clauses: [
      'Definition of confidential information',
      'Obligations of receiving party',
      'Permitted disclosures',
      'Return or destruction of information',
      'No license granted',
      'Remedies for breach',
      'Term and termination',
    ],
  },
  {
    id: '4',
    title: 'Freelance/Consulting Agreement',
    category: 'business',
    country: 'India',
    region: 'Tamil Nadu',
    languages: ['English'],
    description: 'Service agreement for freelancers and consultants. Clearly defines scope of work, payment terms, IP rights, and deliverables.',
    fields: [
      { id: 'client_name', name: 'client_name', label: 'Client/Company Name', type: 'text', required: true },
      { id: 'client_address', name: 'client_address', label: 'Client Address', type: 'textarea', required: true },
      { id: 'freelancer_name', name: 'freelancer_name', label: 'Freelancer/Consultant Name', type: 'text', required: true },
      { id: 'freelancer_address', name: 'freelancer_address', label: 'Freelancer Address', type: 'textarea', required: true },
      { id: 'service_description', name: 'service_description', label: 'Service Description', type: 'textarea', required: true },
      { id: 'project_duration', name: 'project_duration', label: 'Project Duration', type: 'text', required: true },
      { id: 'payment_type', name: 'payment_type', label: 'Payment Type', type: 'select', required: true, options: ['Fixed Price', 'Hourly Rate', 'Monthly Retainer'] },
      { id: 'payment_amount', name: 'payment_amount', label: 'Payment Amount (INR)', type: 'number', required: true },
      { id: 'payment_schedule', name: 'payment_schedule', label: 'Payment Schedule', type: 'select', required: true, options: ['Upon Completion', '50-50 Milestone', '30-70 Milestone', 'Monthly', 'Weekly'] },
      { id: 'gst_applicable', name: 'gst_applicable', label: 'GST Applicable', type: 'checkbox', required: false },
    ],
    clauses: [
      'Scope of services and deliverables',
      'Payment terms and invoicing',
      'Intellectual property ownership',
      'Confidentiality obligations',
      'Independent contractor status',
      'Termination rights',
      'Limitation of liability',
      'Tax responsibilities',
    ],
  },
  {
    id: '5',
    title: 'Promissory Note',
    category: 'financial',
    country: 'India',
    region: 'Tamil Nadu',
    languages: ['English', 'Tamil'],
    description: 'Legal instrument for documenting personal or business loans. Stamped and notarized for enforceability under Negotiable Instruments Act, 1881.',
    fields: [
      { id: 'lender_name', name: 'lender_name', label: 'Lender Name', type: 'text', required: true },
      { id: 'lender_address', name: 'lender_address', label: 'Lender Address', type: 'textarea', required: true },
      { id: 'borrower_name', name: 'borrower_name', label: 'Borrower Name', type: 'text', required: true },
      { id: 'borrower_address', name: 'borrower_address', label: 'Borrower Address', type: 'textarea', required: true },
      { id: 'loan_amount', name: 'loan_amount', label: 'Loan Amount (INR)', type: 'number', required: true },
      { id: 'interest_rate', name: 'interest_rate', label: 'Annual Interest Rate (%)', type: 'number', required: true },
      { id: 'loan_date', name: 'loan_date', label: 'Loan Date', type: 'date', required: true },
      { id: 'repayment_date', name: 'repayment_date', label: 'Repayment Due Date', type: 'date', required: true },
      { id: 'repayment_mode', name: 'repayment_mode', label: 'Repayment Mode', type: 'select', required: true, options: ['Lump Sum', 'Monthly Installments', 'Quarterly Installments'] },
      { id: 'purpose', name: 'purpose', label: 'Purpose of Loan', type: 'textarea', required: false },
    ],
    clauses: [
      'Principal amount acknowledgment',
      'Interest calculation method',
      'Repayment schedule',
      'Late payment penalties',
      'Prepayment rights',
      'Default and remedies',
      'Governing law (Negotiable Instruments Act)',
    ],
  },
  {
    id: '6',
    title: 'Service Agreement',
    category: 'consumer',
    country: 'India',
    region: 'Tamil Nadu',
    languages: ['English'],
    description: 'General service agreement for businesses providing services to consumers. Compliant with Consumer Protection Act, 2019.',
    fields: [
      { id: 'provider_name', name: 'provider_name', label: 'Service Provider Name', type: 'text', required: true },
      { id: 'provider_address', name: 'provider_address', label: 'Provider Address', type: 'textarea', required: true },
      { id: 'customer_name', name: 'customer_name', label: 'Customer Name', type: 'text', required: true },
      { id: 'customer_address', name: 'customer_address', label: 'Customer Address', type: 'textarea', required: true },
      { id: 'service_type', name: 'service_type', label: 'Service Type', type: 'text', required: true },
      { id: 'service_description', name: 'service_description', label: 'Detailed Service Description', type: 'textarea', required: true },
      { id: 'start_date', name: 'start_date', label: 'Service Start Date', type: 'date', required: true },
      { id: 'service_fee', name: 'service_fee', label: 'Service Fee (INR)', type: 'number', required: true },
      { id: 'billing_cycle', name: 'billing_cycle', label: 'Billing Cycle', type: 'select', required: true, options: ['One-time', 'Monthly', 'Quarterly', 'Annually'] },
      { id: 'auto_renewal', name: 'auto_renewal', label: 'Auto-renewal', type: 'checkbox', required: false },
    ],
    clauses: [
      'Service scope and specifications',
      'Fees and payment terms',
      'Service level commitments',
      'Customer obligations',
      'Warranties and disclaimers',
      'Cancellation and refund policy',
      'Dispute resolution mechanism',
      'Data privacy and protection',
    ],
  },
];

// Category Labels
export const categoryLabels: Record<string, string> = {
  employment: 'Employment & Work',
  property: 'Property & Real Estate',
  business: 'Business & Commercial',
  financial: 'Financial',
  insurance: 'Insurance Policies',
  consumer: 'Consumer & Services',
  family: 'Family & Personal',
  legal: 'Legal Proceedings',
};

// Event Type Labels
export const eventTypeLabels: Record<string, string> = {
  contract_expiry: 'Contract Expiry',
  payment_due: 'Payment Due',
  renewal_date: 'Renewal Date',
  review_date: 'Review Date',
  obligation_end: 'Obligation Ends',
  milestone: 'Milestone',
};

// Mock Insurance Documents
export const mockInsuranceDocuments: Document[] = [
  {
    id: 'ins-1',
    title: 'Health Insurance - Star Health Premier',
    category: 'insurance',
    documentType: 'Health Insurance Policy',
    status: 'active',
    filePath: '/documents/health_star.pdf',
    fileType: 'pdf',
    fileSize: 4200000,
    pages: 28,
    uploadedAt: new Date('2024-01-15'),
    signedDate: new Date('2024-01-15'),
    startDate: new Date('2024-02-01'),
    endDate: new Date('2025-01-31'),
    parties: ['You (Rajesh Kumar)', 'Star Health Insurance Co. Ltd.'],
    tags: ['health', 'insurance', 'active'],
    country: 'India',
    region: 'Tamil Nadu',
    language: 'English',
    metadata: {
      policyNumber: 'SH-2024-TN-123456',
      premium: 18500,
      coverage: 500000,
      insuranceType: 'health',
    },
    upcomingEvents: 1,
    pendingTasks: 0,
  },
  {
    id: 'ins-2',
    title: 'Car Insurance - HDFC ERGO Comprehensive',
    category: 'insurance',
    documentType: 'Auto Insurance Policy',
    status: 'active',
    filePath: '/documents/auto_hdfc.pdf',
    fileType: 'pdf',
    fileSize: 2800000,
    pages: 15,
    uploadedAt: new Date('2024-06-10'),
    signedDate: new Date('2024-06-10'),
    startDate: new Date('2024-06-15'),
    endDate: new Date('2025-06-14'),
    parties: ['You (Rajesh Kumar)', 'HDFC ERGO General Insurance Co. Ltd.'],
    tags: ['auto', 'insurance', 'comprehensive'],
    country: 'India',
    region: 'Tamil Nadu',
    language: 'English',
    metadata: {
      policyNumber: 'HDFC-AUTO-2024-456789',
      premium: 12500,
      coverage: 800000,
      insuranceType: 'auto',
      vehicleNumber: 'TN 09 AB 1234',
    },
    upcomingEvents: 1,
    pendingTasks: 0,
  },
  {
    id: 'ins-3',
    title: 'Term Life Insurance - LIC Tech Term Plus',
    category: 'insurance',
    documentType: 'Life Insurance Policy',
    status: 'active',
    filePath: '/documents/life_lic.pdf',
    fileType: 'pdf',
    fileSize: 3500000,
    pages: 22,
    uploadedAt: new Date('2023-03-20'),
    signedDate: new Date('2023-03-20'),
    startDate: new Date('2023-04-01'),
    endDate: new Date('2043-03-31'),
    parties: ['You (Rajesh Kumar)', 'LIC of India'],
    tags: ['life', 'insurance', 'term'],
    country: 'India',
    region: 'Tamil Nadu',
    language: 'English',
    metadata: {
      policyNumber: 'LIC-TERM-2023-789012',
      premium: 15000,
      coverage: 10000000,
      insuranceType: 'life',
    },
    upcomingEvents: 1,
    pendingTasks: 0,
  },
  {
    id: 'ins-4',
    title: 'Home Insurance - ICICI Lombard',
    category: 'insurance',
    documentType: 'Property Insurance Policy',
    status: 'active',
    filePath: '/documents/home_icici.pdf',
    fileType: 'pdf',
    fileSize: 3200000,
    pages: 18,
    uploadedAt: new Date('2024-08-05'),
    signedDate: new Date('2024-08-05'),
    startDate: new Date('2024-08-15'),
    endDate: new Date('2025-08-14'),
    parties: ['You (Rajesh Kumar)', 'ICICI Lombard General Insurance Co. Ltd.'],
    tags: ['property', 'insurance', 'home'],
    country: 'India',
    region: 'Tamil Nadu',
    language: 'English',
    metadata: {
      policyNumber: 'ICICI-HOME-2024-345678',
      premium: 8500,
      coverage: 3000000,
      insuranceType: 'property',
    },
    upcomingEvents: 1,
    pendingTasks: 0,
  },
];

// Mock Insurance Policies with detailed information
export const mockInsurancePolicies: InsurancePolicy[] = [
  {
    id: 'pol-1',
    documentId: 'ins-1',
    policyNumber: 'SH-2024-TN-123456',
    insuranceType: 'health',
    provider: 'Star Health Insurance Co. Ltd.',
    policyHolder: 'Rajesh Kumar',
    insuredMembers: ['Rajesh Kumar', 'Priya Kumar (Spouse)', 'Aarav Kumar (Son)', 'Anaya Kumar (Daughter)'],
    premiumAmount: 18500,
    premiumFrequency: 'yearly',
    coverageAmount: 500000,
    startDate: new Date('2024-02-01'),
    endDate: new Date('2025-01-31'),
    renewalDate: new Date('2025-02-01'),
    gracePeriod: 30,
    status: 'active',
    coverage: [
      { type: 'Hospitalization', amount: 500000, description: 'Room rent, ICU, surgery, medications' },
      { type: 'Pre-hospitalization', amount: 10000, description: '30 days before admission' },
      { type: 'Post-hospitalization', amount: 10000, description: '60 days after discharge' },
      { type: 'Ambulance', amount: 2000, description: 'Per hospitalization' },
      { type: 'Day Care Procedures', amount: 500000, description: 'Covered procedures' },
    ],
    exclusions: [
      'Cosmetic/aesthetic procedures',
      'Pre-existing diseases for first 2 years',
      'Maternity expenses for first 9 months',
      'Dental treatment (unless accident-related)',
      'Alternative therapies (Ayurveda, Homeopathy)',
    ],
    benefits: [
      { name: 'No Claim Bonus', description: '10% increase in sum insured every claim-free year', limit: 100 },
      { name: 'Health Check-up', description: 'Annual health check-up for all members' },
      { name: 'Second Opinion', description: 'Expert medical opinion service' },
    ],
    claims: [],
    healthInsurance: {
      network: 'both',
      networkHospitals: ['Apollo Hospitals', 'Fortis Malar', 'MIOT Hospitals', 'Kauvery Hospital'],
      roomRentLimit: 5000,
      copayment: 0,
      waitingPeriod: 24,
      preExistingDiseaseCovered: true,
      maternityCovered: true,
    },
  },
  {
    id: 'pol-2',
    documentId: 'ins-2',
    policyNumber: 'HDFC-AUTO-2024-456789',
    insuranceType: 'auto',
    provider: 'HDFC ERGO General Insurance Co. Ltd.',
    policyHolder: 'Rajesh Kumar',
    premiumAmount: 12500,
    premiumFrequency: 'yearly',
    coverageAmount: 800000,
    startDate: new Date('2024-06-15'),
    endDate: new Date('2025-06-14'),
    renewalDate: new Date('2025-06-15'),
    gracePeriod: 0,
    status: 'active',
    coverage: [
      { type: 'Own Damage', amount: 800000, description: 'IDV coverage for vehicle damage' },
      { type: 'Third Party Liability', amount: 'Unlimited', description: 'Legal liability coverage' },
      { type: 'Personal Accident Cover', amount: 1500000, description: 'For owner-driver' },
    ],
    exclusions: [
      'Consequential loss (depreciation)',
      'Mechanical/electrical breakdown',
      'Wear and tear',
      'Drunk driving',
      'Unlicensed driving',
    ],
    benefits: [
      { name: 'Zero Depreciation', description: 'No depreciation on parts during claim' },
      { name: 'Road Side Assistance', description: '24x7 roadside assistance' },
      { name: 'Engine Protection', description: 'Water damage to engine covered' },
    ],
    autoInsurance: {
      vehicleNumber: 'TN 09 AB 1234',
      vehicleMake: 'Hyundai',
      vehicleModel: 'Creta',
      vehicleYear: 2023,
      coverageType: 'comprehensive',
      idv: 800000,
      ncb: 20,
      addOns: ['Zero Depreciation', 'Engine Protection', 'Road Side Assistance', 'Consumables Cover'],
    },
  },
  {
    id: 'pol-3',
    documentId: 'ins-3',
    policyNumber: 'LIC-TERM-2023-789012',
    insuranceType: 'life',
    provider: 'LIC of India',
    policyHolder: 'Rajesh Kumar',
    premiumAmount: 15000,
    premiumFrequency: 'yearly',
    coverageAmount: 10000000,
    startDate: new Date('2023-04-01'),
    endDate: new Date('2043-03-31'),
    renewalDate: new Date('2026-04-01'),
    gracePeriod: 30,
    status: 'active',
    coverage: [
      { type: 'Death Benefit', amount: 10000000, description: 'Sum assured on death' },
      { type: 'Terminal Illness', amount: 5000000, description: '50% advance payout for terminal illness' },
    ],
    exclusions: [
      'Suicide within first 12 months',
    ],
    lifeInsurance: {
      policyType: 'term',
      sumAssured: 10000000,
      nominees: [
        { name: 'Priya Kumar', relationship: 'Spouse', share: 100 },
      ],
      riders: [
        { name: 'Accidental Death Benefit', coverageAmount: 10000000, premium: 1200 },
        { name: 'Critical Illness Rider', coverageAmount: 1000000, premium: 800 },
      ],
    },
  },
  {
    id: 'pol-4',
    documentId: 'ins-4',
    policyNumber: 'ICICI-HOME-2024-345678',
    insuranceType: 'property',
    provider: 'ICICI Lombard General Insurance Co. Ltd.',
    policyHolder: 'Rajesh Kumar',
    premiumAmount: 8500,
    premiumFrequency: 'yearly',
    coverageAmount: 3000000,
    startDate: new Date('2024-08-15'),
    endDate: new Date('2025-08-14'),
    renewalDate: new Date('2025-08-15'),
    gracePeriod: 15,
    status: 'active',
    coverage: [
      { type: 'Building', amount: 2000000, description: 'Structure damage' },
      { type: 'Contents', amount: 1000000, description: 'Household items, furniture' },
      { type: 'Temporary Accommodation', amount: 100000, description: 'If house becomes uninhabitable' },
      { type: 'Public Liability', amount: 500000, description: 'Third party injury/damage' },
    ],
    exclusions: [
      'Normal wear and tear',
      'War and nuclear risks',
      'Wilful damage',
      'Consequential loss',
    ],
    benefits: [
      { name: 'Automatic Index Linking', description: 'Sum insured adjusts with inflation' },
      { name: 'Alternative Accommodation', description: 'Hotel stay if home damaged' },
    ],
    propertyInsurance: {
      propertyAddress: 'Flat 4B, Landmark Apartments, Anna Nagar, Chennai - 600040',
      propertyType: 'home',
      buildingValue: 2000000,
      contentsValue: 1000000,
      coveredPerils: [
        'Fire and lightning',
        'Explosion',
        'Earthquake',
        'Flood and inundation',
        'Storm, cyclone, typhoon',
        'Burglary and theft',
        'Riot and strike damage',
        'Malicious damage',
      ],
      deductible: 5000,
    },
  },
];

// Mock Insurance Summary
export const mockInsuranceSummary: InsuranceSummary = {
  totalPolicies: 4,
  activePolicies: 4,
  expiringPolicies: 1,
  totalPremium: 54500,
  totalCoverage: 14300000,
  byType: {
    health: {
      count: 1,
      totalCoverage: 500000,
      totalPremium: 18500,
    },
    auto: {
      count: 1,
      totalCoverage: 800000,
      totalPremium: 12500,
    },
    life: {
      count: 1,
      totalCoverage: 10000000,
      totalPremium: 15000,
    },
    property: {
      count: 1,
      totalCoverage: 3000000,
      totalPremium: 8500,
    },
  },
  upcomingRenewals: [
    {
      policyId: 'pol-1',
      policyNumber: 'SH-2024-TN-123456',
      insuranceType: 'health',
      renewalDate: new Date('2025-02-01'),
      premiumAmount: 18500,
    },
    {
      policyId: 'pol-2',
      policyNumber: 'HDFC-AUTO-2024-456789',
      insuranceType: 'auto',
      renewalDate: new Date('2025-06-15'),
      premiumAmount: 12500,
    },
  ],
  recentClaims: [],
};
